### ISSUE TITLE
Any chance of using it with Django 1.9?

### ISSUE THREAD

**Issue by engineervix** [agusmakmun/django-contact-widget#1]
Hi @agusmakmun, this looks great, it's exactly what I have looking for! I've seen that the requirements ae Django>=1.10, any chance this can work with Django 1.9.9? What modifications can I make to make it work with Django 1.9.9?

Thanks!

**Comment by agusmakmun** [comment]
Hello @engineervix, i never test this tool to the Django<=1.9.9, but i think it should be work well..
you can try with this to ignoring the requirment:

```
$ pip install django-contact-widget --no-dependencies
```

**Comment by engineervix** [comment]
Hi @agusmakmun, I decided to just switch to django 1.10! Thanks!
